### ISSUE TITLE
Telegram Mini Apps don't work on Linux

### ISSUE THREAD

**Issue by gagarin55** [telegramdesktop/tdesktop#28044]
### Steps to reproduce

It has been discussed already but I still didn't get is Telegram Mini Apps should work on Linux OS or not ?
Neither the wallet nor any other application is working.

### Expected behaviour

Telegram Mini Apps should work.

### Actual behaviour

Telegram Mini Apps don't work.

### Operating system

Linux Mint 21

### Version of Telegram Desktop

5.1.4

### Installation source

Static binary from official website

### Logs

```shell
No errors in log file.
```

**Comment by ilya-fedin** [comment]
> It has been discussed already but I still didn't get is Telegram Mini Apps should work on Linux OS or not ?

Sometimes. They are plenty bugged.

> Telegram Mini Apps don't work.

Please be more concrete. Or if you can't, provide a screenshot.

**Comment by gagarin55** [comment]
![image](https://github.com/telegramdesktop/tdesktop/assets/18405789/567a4aaf-922a-4f89-8614-62f221033a0b)
Same for all apps.

```
System:
  Kernel: 5.15.0-107-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 5.4.12
    tk: GTK 3.24.33 wm: Mutter dm: LightDM Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
Machine:
  Type: Virtualbox System: innotek GmbH product: VirtualBox v: 1.2 serial: <superuser required>
    Chassis: Oracle Corporation type: 1 serial: <superuser required>
  Mobo: Oracle model: VirtualBox v: 1.2 serial: <superuser required> BIOS: innotek GmbH
    v: VirtualBox date: 12/01/2006
Graphics:
  Device-1: VMware SVGA II Adapter driver: vmwgfx v: 2.19.0.0 ports: active: Virtual-1
    empty: Virtual-2, Virtual-3, Virtual-4, Virtual-5, Virtual-6, Virtual-7, Virtual-8
    bus-ID: 00:02.0 chip-ID: 15ad:0405
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: vmware
    unloaded: fbdev,modesetting,vesa gpu: vmwgfx display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1124 s-dpi: 96
  Monitor-1: Virtual1 mapped: Virtual-1 res: 1920x1124 size: N/A
  OpenGL: renderer: SVGA3D; build: RELEASE; LLVM; v: 4.1 Mesa 23.2.1-1ubuntu3.1~22.04.2
    direct render: Yes

```
