### ISSUE TITLE
"Empty message" when only the photo is

### ISSUE THREAD

**Issue by Lonami** [telegramdesktop/tdesktop#5867]
See https://t.me/telethonofftopic/179050 for an example. This is what Telegram Desktop v1.6.3 shows:
![image](https://user-images.githubusercontent.com/6297805/55307458-e7d69b00-5457-11e9-9659-90e2f0a92628.png)

This is what the message actually has:
```yaml
Message:
  id: 179050
  to_id: PeerChannel: channel_id: 1200633650  
  date: 2019-03-01 13:57:18
  message: 'User Info:\n\nFirst Name: Deleted Account\nUser id: 473862645\nPermanent user link: link\n\nYou have 5 chats in common with this user'
  out: False
  mentioned: False
  media_unread: False
  silent: False
  post: False
  from_scheduled: False
  from_id: 416195206
  reply_to_msg_id: 8
  media: MessageMediaPhoto:
    photo: PhotoEmpty: id: 2035224563527297246      
  entities: 
    - MessageEntityBold:
        offset: 0
        length: 10      
    - MessageEntityCode:
        offset: 49
        length: 9      
    - MessageEntityCode:
        offset: 95
        length: 1
```

It would be helpful if it showed at least the caption, and ideally (if no photo is shown), indicate that the photo is hidden.
